def a_function(turtle, letter):
    if letter == 'A':
        turtle.forward(30)
        turtle.right(45)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(135)
        turtle.forward(40)
        turtle.penup()
        turtle.backward(40)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(30)
    elif letter == 'a':
        turtle.penup()
        turtle.forward(35)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(35)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(30)
        turtle.penup()
        turtle.right(90)
        turtle.forward(20)
        turtle.left(45)
        turtle.forward(5)
        turtle.left(45)
        turtle.forward(5)
        turtle.right(90)
    else:
        return


def b_function(turtle, letter):
    if letter == 'B':
        turtle.forward(60)
        turtle.right(105)
        turtle.forward(30)
        turtle.right(75)
        turtle.forward(15)
        turtle.right(75)
        turtle.forward(30)
        turtle.left(147)
        turtle.forward(30)
        turtle.right(72)
        turtle.forward(15)
        turtle.right(75)
        turtle.forward(30)
        turtle.left(165)
        turtle.penup()
        turtle.forward(20)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'b':
        turtle.forward(60)
        turtle.backward(35)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.backward(25)
        turtle.left(90)
    else:
        return


def c_function(turtle, letter):
    if letter == 'C':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.penup()
        turtle.right(90)
        turtle.forward(60)
        turtle.right(90)
        turtle.pendown()
        turtle.forward(30)
        turtle.penup()
        turtle.right(180)
        turtle.forward(30)
        turtle.pendown()
        turtle.right(90)
    elif letter == 'c':
        turtle.right(90)
        turtle.forward(5)
        turtle.left(45)
        turtle.forward(5)
        turtle.left(45)
        turtle.backward(5)
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.penup()
        turtle.forward(40)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(25)
        turtle.right(180)
        turtle.penup()
        turtle.forward(25)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def d_function(turtle, letter):
    if letter == 'D':
        turtle.forward(60)
        turtle.right(105)
        turtle.forward(30)
        turtle.right(75)
        turtle.forward(45)
        turtle.right(75)
        turtle.forward(30)
        turtle.left(165)
        turtle.penup()
        turtle.forward(20)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'd':
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.penup()
        turtle.forward(35)
        turtle.pendown()
        turtle.backward(60)
        turtle.left(90)
        turtle.forward(25)
        turtle.backward(25)
        turtle.left(90)
    else:
        return


def e_function(turtle, letter):
    if letter == 'E':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(180)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.right(180)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
    elif letter == 'e':
        turtle.forward(35)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(90)
        turtle.forward(25)
        turtle.left(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(25)
        turtle.right(90)
    else:
        return


def f_function(turtle, letter):
    if letter == 'F':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(180)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.right(180)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(30)
        turtle.penup()
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'f':
        turtle.right(90)
        turtle.penup()
        turtle.forward(15)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(15)
        turtle.penup()
        turtle.right(90)
        turtle.forward(10)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.backward(20)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(35)
        turtle.left(90)
        turtle.penup()
        turtle.forward(15)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def g_function(turtle, letter):
    if letter == 'G':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(15)
        turtle.penup()
        turtle.forward(15)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(20)
        turtle.backward(20)
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
    elif letter == 'g':
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(90)
        turtle.backward(20)
    else:
        return


def h_function(turtle, letter):
    if letter == 'H':
        turtle.forward(60)
        turtle.backward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.backward(60)
        turtle.right(180)
    elif letter == 'h':
        turtle.forward(60)
        turtle.backward(35)
        turtle.right(90)
        turtle.forward(25)
        turtle.right(90)
        turtle.forward(25)
    else:
        return


def i_function(turtle, letter):
    if letter == "I":
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(15)
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.forward(15)
        turtle.backward(30)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.forward(15)
        turtle.right(90)
    elif letter == 'i':
        turtle.penup()
        turtle.right(90)
        turtle.forward(5)
        turtle.left(90)
        turtle.pendown()
        turtle.forward(25)
        turtle.penup()
        turtle.forward(5)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(5)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(5)
        turtle.right(90)
        turtle.penup()
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(5)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def j_function(turtle, letter):
    if letter == 'J':
        turtle.forward(20)
        turtle.backward(20)
        turtle.right(90)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.forward(15)
        turtle.backward(30)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.penup()
        turtle.forward(15)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'j':
        turtle.right(45)
        turtle.forward(30)
        turtle.left(45)
        turtle.penup()
        turtle.forward(5)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(5)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(5)
        turtle.right(90)
        turtle.penup()
        turtle.forward(5)
        turtle.pendown()
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(20)
        turtle.backward(20)
        turtle.left(90)
        turtle.backward(20)
    else:
        return


def k_function(turtle, letter):
    if letter == 'K':
        turtle.forward(60)
        turtle.backward(30)
        turtle.right(45)
        turtle.forward(43)
        turtle.backward(43)
        turtle.right(90)
        turtle.forward(43)
        turtle.right(45)
    elif letter == 'k':
        turtle.forward(60)
        turtle.backward(35)
        turtle.right(55)
        turtle.forward(20)
        turtle.backward(20)
        turtle.right(90)
        turtle.forward(32)
        turtle.right(35)
    else:
        return


def l_function(turtle, letter):
    if letter == 'L':
        turtle.forward(60)
        turtle.backward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
    elif letter == 'l':
        turtle.penup()
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(5)
        turtle.pendown()
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.forward(10)
        turtle.penup()
        turtle.forward(5)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def m_function(turtle, letter):
    if letter == 'M':
        turtle.forward(60)
        turtle.right(155)
        turtle.forward(30)
        turtle.left(125)
        turtle.forward(30)
        turtle.right(150)
        turtle.forward(60)
    elif letter == 'm':
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
    else:
        return


def n_function(turtle, letter):
    if letter == 'N':
        turtle.forward(60)
        turtle.right(155)
        turtle.forward(65)
        turtle.left(155)
        turtle.forward(60)
        turtle.backward(60)
        turtle.right(180)
    elif letter == 'n':
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
    else:
        return


def o_function(turtle, letter):
    if letter == 'O':
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(40)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
    elif letter == 'o':
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(180)
        turtle.forward(30)
        turtle.right(90)
    else:
        return


def p_function(turtle, letter):
    if letter == 'P':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(30)
        turtle.penup()
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.pendown()
    elif letter == 'p':
        turtle.backward(20)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.left(180)
        turtle.penup()
        turtle.forward(30)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def q_function(turtle, letter):
    if letter == 'Q':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.penup()
        turtle.right(145)
        turtle.forward(20)
        turtle.right(90)
        turtle.pendown()
        turtle.forward(25)
        turtle.left(140)
        turtle.penup()
        turtle.forward(10)
        turtle.right(175)
        turtle.pendown()
    elif letter == 'q':
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.backward(20)
    else:
        return


def r_function(turtle, letter):
    if letter == 'R':
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.right(45)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(15)
        turtle.left(125)
        turtle.forward(40)
        turtle.right(35)
        turtle.pendown()
    elif letter == 'r':
        turtle.penup()
        turtle.right(90)
        turtle.forward(5)
        turtle.left(90)
        turtle.pendown()
        turtle.forward(30)
        turtle.left(45)
        turtle.forward(10)
        turtle.backward(10)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(45)
        turtle.forward(20)
        turtle.right(90)
        turtle.penup()
        turtle.forward(35)
        turtle.pendown()
    else:
        return


def s_function(turtle, letter):
    if letter == 'S':
        turtle.penup()
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(180)
        turtle.pendown()
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(180)
        turtle.penup()
        turtle.forward(30)
        turtle.right(90)
        turtle.pendown()
    elif letter == 's':
        turtle.penup()
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(180)
        turtle.pendown()
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(180)
        turtle.penup()
        turtle.forward(30)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def t_function(turtle, letter):
    if letter == 'T':
        turtle.penup()
        turtle.right(90)
        turtle.forward(15)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.forward(15)
        turtle.backward(30)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(60)
        turtle.left(90)
        turtle.penup()
        turtle.forward(15)
        turtle.right(90)
        turtle.pendown()
    elif letter == 't':
        turtle.right(90)
        turtle.penup()
        turtle.forward(15)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(60)
        turtle.backward(15)
        turtle.right(90)
        turtle.forward(10)
        turtle.backward(20)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(45)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(20)
        turtle.backward(20)
        turtle.penup()
        turtle.right(90)
        turtle.forward(5)
        turtle.right(90)
        turtle.pendown()
    else:
        return


def u_function(turtle, letter):
    if letter == 'U':
        turtle.forward(60)
        turtle.backward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(60)
        turtle.right(180)
        turtle.forward(60)
    elif letter == 'u':
        turtle.right(90)
        turtle.forward(5)
        turtle.left(45)
        turtle.forward(5)
        turtle.left(45)
        turtle.forward(25)
        turtle.backward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.backward(25)
        turtle.right(135)
        turtle.forward(5)
        turtle.left(45)
        turtle.forward(5)
        turtle.right(90)
    else:
        return


def v_function(turtle, letter):
    if letter == 'V':
        turtle.penup()
        turtle.forward(55)
        turtle.right(155)
        turtle.pendown()
        turtle.forward(60)
        turtle.left(125)
        turtle.forward(60)
        turtle.right(150)
        turtle.penup()
        turtle.forward(55)
        turtle.pendown()
        # turtle.left(90)
    elif letter == 'v':
        turtle.penup()
        turtle.forward(40)
        turtle.right(155)
        turtle.pendown()
        turtle.forward(40)
        turtle.left(125)
        turtle.forward(40)
        turtle.right(150)
        turtle.penup()
        turtle.forward(35)
        turtle.pendown()
    else:
        return


def w_function(turtle, letter):
    if letter == 'W':
        turtle.penup()
        turtle.forward(55)
        turtle.right(165)
        turtle.pendown()
        turtle.forward(60)
        turtle.left(152)
        turtle.forward(60)
        turtle.right(167)
        turtle.left(10)
        turtle.forward(60)
        turtle.left(152)
        turtle.forward(60)
        turtle.right(162)
        turtle.penup()
        turtle.forward(55)
        turtle.pendown()
    elif letter == 'w':
        turtle.penup()
        turtle.forward(35)
        turtle.right(165)
        turtle.pendown()
        turtle.forward(40)
        turtle.left(152)
        turtle.forward(40)
        turtle.right(167)
        turtle.left(10)
        turtle.forward(40)
        turtle.left(152)
        turtle.forward(40)
        turtle.right(162)
        turtle.penup()
        turtle.forward(35)
        turtle.pendown()
    else:
        return


def x_function(turtle, letter):
    if letter == 'X':
        turtle.right(30)
        turtle.forward(65)
        turtle.penup()
        turtle.left(120)
        turtle.forward(30)
        turtle.pendown()
        turtle.left(120)
        turtle.forward(65)
        turtle.right(30)
    elif letter == 'x':
        turtle.right(42)
        turtle.forward(40)
        turtle.penup()
        turtle.left(130)
        turtle.forward(25)
        turtle.pendown()
        turtle.left(130)
        turtle.forward(40)
        turtle.right(42)
    else:
        return


def y_function(turtle, letter):
    if letter == 'Y':
        turtle.penup()
        turtle.right(90)
        turtle.forward(15)
        turtle.pendown()
        turtle.left(90)
        turtle.forward(30)
        turtle.left(30)
        turtle.forward(30)
        turtle.backward(30)
        turtle.right(60)
        turtle.forward(30)
        turtle.right(150)
        turtle.penup()
        turtle.forward(60)
        turtle.pendown()
    elif letter == 'y':
        turtle.forward(30)
        turtle.right(90)
        turtle.penup()
        turtle.forward(30)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(30)
        turtle.backward(30)
        turtle.left(90)
        turtle.backward(20)
    else:
        return


def z_function(turtle, letter):
    if letter == 'Z':
        turtle.penup()
        turtle.forward(60)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(30)
        turtle.right(120)
        turtle.forward(60)
        turtle.left(120)
        turtle.forward(30)
        turtle.right(90)
    elif letter == 'z':
        turtle.penup()
        turtle.forward(30)
        turtle.pendown()
        turtle.right(90)
        turtle.forward(25)
        turtle.right(130)
        turtle.forward(40)
        turtle.left(130)
        turtle.forward(25)
        turtle.right(90)
    else:
        return

